FROM alpine:3.21

ENV PATH /srv/node_modules/.bin:$PATH
ENV NODE_PATH /srv/node_modules
ENV PYTHONUNBUFFERED 1
ENV PYTHONDONTWRITEBYTECODE 1

WORKDIR /srv
ADD api/scripts deployment/podman/dev.run.sh /usr/local/bin/
ADD deployment/podman/containers.conf deployment/podman/docleaner.conf /root
RUN apk add fuse-overlayfs libmagic npm podman py3-pip; \
    mv /root/containers.conf /etc/containers/containers.conf; \
    mv /root/docleaner.conf /etc/docleaner.conf; \
    adduser -D -u 1000 podman; \
    echo -e "podman:1:999\npodman:1001:64535" >/etc/subuid; \
    echo -e "podman:1:999\npodman:1001:64535" >/etc/subgid; \
    mkdir -p /srv/src/docleaner; \
    ln -s /mnt/requirements/ /srv/requirements; \
    ln -s /mnt/pytest.ini /srv/pytest.ini; \
    ln -s /mnt/setup.py /srv/setup.py; \
    ln -s /mnt/src/docleaner/api /srv/src/docleaner; \
    ln -s /mnt/tests /srv; \
    ln -s /mnt/src/docleaner/api/entrypoints/web/package.json /srv/package.json; \
    ln -s /mnt/src/docleaner/api/entrypoints/web/webpack.config.js /srv/webpack.config.js; \
    ln -s /mnt/src/docleaner/api/entrypoints/web/static /srv/static
CMD ["/usr/local/bin/dev.run.sh"]
