FROM alpine:3.21

COPY analyze exiftool.cfg process /opt/
RUN apk add tini bash exiftool qpdf python3 py3-pip; \
    python3 -m venv /opt/venv; \
    /opt/venv/bin/pip3 install pyhanko
ENTRYPOINT ["/sbin/tini", "--"]
CMD ["sleep", "infinity"]
