#!/usr/bin/env python3
import json
import sys

from PyPDF2 import PdfReader


if __name__ == "__main__":
    if len(sys.argv) != 2:
        print("Usage: analyze <path_to_pdf>")
        sys.exit(1)
    reader = PdfReader(sys.argv[1])
    metadata = {}
    for key, val in dict(reader.metadata).items():
        if key.startswith("/"):
            key = key[1:]
        metadata[key] = val
    print(json.dumps(metadata))
