FROM alpine:3.16

ADD deployment/docker/api.run.sh /usr/local/bin/
ADD dist/docleaner_api*.whl /opt
RUN apk add libmagic py3-pip; \
    pip3 install /opt/docleaner_api*.whl
CMD ["/usr/local/bin/api.run.sh"]
