FROM alpine:3.16

ENV PYTHONUNBUFFERED 1
ENV PYTHONDONTWRITEBYTECODE 1

WORKDIR /srv
ADD api/requirements api/pytest.ini api/setup.py /srv/
ADD api/scripts /usr/local/bin/
RUN apk add libmagic py3-pip; \
    pip3 install -r /srv/development.txt; \
    mkdir -p /srv/src/docleaner/api /srv/tests; \
    pip3 install -e /srv
