version: "3"
services:

  api:
    environment:
      - DOCLEANER_URL=https://docleaner.example.com
    image: docleaner/api:latest
    networks:
      - docleaner
    restart: unless-stopped
    volumes:
      - <path/to/podman.sock>:/run/podman.sock

  proxy:
    image: nginx:stable
    networks:
      - docleaner
    ports:
      - "80:8080"
      - "443:8443"
    restart: unless-stopped
    volumes:
      - <path/to/nginx.conf>:/etc/nginx/nginx.conf

  database:
    image: mongo:6
    networks:
      - docleaner
    restart: unless-stopped
    volumes:
      - <path/to/data>:/data/db

networks:
  docleaner: