#!/usr/bin/env sh
# Performs type checking of the entire codebase, meant to be run from within the api container during development
MYPYPATH=/srv/src/ /srv/venv/bin/mypy --namespace-packages --explicit-package-bases --strict src/ tests/
