#!/usr/bin/env python3
import json
import sys


if __name__ == "__main__":
    if len(sys.argv) != 4:
        print("Usage: analyze <path_to_pdf> <result_path> <params_path>")
        sys.exit(1)
    src_path = sys.argv[1]
    result_path = sys.argv[2]
    params_path = sys.argv[3]
    metadata = {"primary": {}, "embeds": {}, "signed": False}
    with open(result_path, "w") as f:
        json.dump(metadata, f)
